package opencl

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for copypadmul2 kernel invocation
type copypadmul2_args_t struct {
	arg_dst    unsafe.Pointer
	arg_Dx     int
	arg_Dy     int
	arg_Dz     int
	arg_src    unsafe.Pointer
	arg_Sx     int
	arg_Sy     int
	arg_Sz     int
	arg_Ms_    unsafe.Pointer
	arg_Ms_mul float32
	arg_vol    unsafe.Pointer
	argptr     [11]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for copypadmul2 kernel invocation
var copypadmul2_args copypadmul2_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	copypadmul2_args.argptr[0] = unsafe.Pointer(&copypadmul2_args.arg_dst)
	copypadmul2_args.argptr[1] = unsafe.Pointer(&copypadmul2_args.arg_Dx)
	copypadmul2_args.argptr[2] = unsafe.Pointer(&copypadmul2_args.arg_Dy)
	copypadmul2_args.argptr[3] = unsafe.Pointer(&copypadmul2_args.arg_Dz)
	copypadmul2_args.argptr[4] = unsafe.Pointer(&copypadmul2_args.arg_src)
	copypadmul2_args.argptr[5] = unsafe.Pointer(&copypadmul2_args.arg_Sx)
	copypadmul2_args.argptr[6] = unsafe.Pointer(&copypadmul2_args.arg_Sy)
	copypadmul2_args.argptr[7] = unsafe.Pointer(&copypadmul2_args.arg_Sz)
	copypadmul2_args.argptr[8] = unsafe.Pointer(&copypadmul2_args.arg_Ms_)
	copypadmul2_args.argptr[9] = unsafe.Pointer(&copypadmul2_args.arg_Ms_mul)
	copypadmul2_args.argptr[10] = unsafe.Pointer(&copypadmul2_args.arg_vol)
}

// Wrapper for copypadmul2 OpenCL kernel, asynchronous.
func k_copypadmul2_async(dst unsafe.Pointer, Dx int, Dy int, Dz int, src unsafe.Pointer, Sx int, Sy int, Sz int, Ms_ unsafe.Pointer, Ms_mul float32, vol unsafe.Pointer, cfg *config, events []*cl.Event, launchQueue *cl.CommandQueue) *cl.Event {
	if Synchronous { // debug
		launchQueue.Finish()
		timer.Start("copypadmul2")
	}

	copypadmul2_args.Lock()
	defer copypadmul2_args.Unlock()

	copypadmul2_args.arg_dst = dst
	copypadmul2_args.arg_Dx = Dx
	copypadmul2_args.arg_Dy = Dy
	copypadmul2_args.arg_Dz = Dz
	copypadmul2_args.arg_src = src
	copypadmul2_args.arg_Sx = Sx
	copypadmul2_args.arg_Sy = Sy
	copypadmul2_args.arg_Sz = Sz
	copypadmul2_args.arg_Ms_ = Ms_
	copypadmul2_args.arg_Ms_mul = Ms_mul
	copypadmul2_args.arg_vol = vol

	SetKernelArgWrapper("copypadmul2", 0, dst)
	SetKernelArgWrapper("copypadmul2", 1, Dx)
	SetKernelArgWrapper("copypadmul2", 2, Dy)
	SetKernelArgWrapper("copypadmul2", 3, Dz)
	SetKernelArgWrapper("copypadmul2", 4, src)
	SetKernelArgWrapper("copypadmul2", 5, Sx)
	SetKernelArgWrapper("copypadmul2", 6, Sy)
	SetKernelArgWrapper("copypadmul2", 7, Sz)
	SetKernelArgWrapper("copypadmul2", 8, Ms_)
	SetKernelArgWrapper("copypadmul2", 9, Ms_mul)
	SetKernelArgWrapper("copypadmul2", 10, vol)

	//	args := copypadmul2_args.argptr[:]
	event := LaunchKernel("copypadmul2", cfg.Grid, cfg.Block, launchQueue, events)

	if Synchronous { // debug
		launchQueue.Finish()
		timer.Stop("copypadmul2")
	}

	return event
}
