package opencl

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for adddmi kernel invocation
type adddmi_args_t struct {
	arg_Hx      unsafe.Pointer
	arg_Hy      unsafe.Pointer
	arg_Hz      unsafe.Pointer
	arg_mx      unsafe.Pointer
	arg_my      unsafe.Pointer
	arg_mz      unsafe.Pointer
	arg_Ms_     unsafe.Pointer
	arg_Ms_mul  float32
	arg_aLUT2d  unsafe.Pointer
	arg_dLUT2d  unsafe.Pointer
	arg_regions unsafe.Pointer
	arg_cx      float32
	arg_cy      float32
	arg_cz      float32
	arg_Nx      int
	arg_Ny      int
	arg_Nz      int
	arg_PBC     uint8
	arg_OpenBC  uint8
	argptr      [19]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for adddmi kernel invocation
var adddmi_args adddmi_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	adddmi_args.argptr[0] = unsafe.Pointer(&adddmi_args.arg_Hx)
	adddmi_args.argptr[1] = unsafe.Pointer(&adddmi_args.arg_Hy)
	adddmi_args.argptr[2] = unsafe.Pointer(&adddmi_args.arg_Hz)
	adddmi_args.argptr[3] = unsafe.Pointer(&adddmi_args.arg_mx)
	adddmi_args.argptr[4] = unsafe.Pointer(&adddmi_args.arg_my)
	adddmi_args.argptr[5] = unsafe.Pointer(&adddmi_args.arg_mz)
	adddmi_args.argptr[6] = unsafe.Pointer(&adddmi_args.arg_Ms_)
	adddmi_args.argptr[7] = unsafe.Pointer(&adddmi_args.arg_Ms_mul)
	adddmi_args.argptr[8] = unsafe.Pointer(&adddmi_args.arg_aLUT2d)
	adddmi_args.argptr[9] = unsafe.Pointer(&adddmi_args.arg_dLUT2d)
	adddmi_args.argptr[10] = unsafe.Pointer(&adddmi_args.arg_regions)
	adddmi_args.argptr[11] = unsafe.Pointer(&adddmi_args.arg_cx)
	adddmi_args.argptr[12] = unsafe.Pointer(&adddmi_args.arg_cy)
	adddmi_args.argptr[13] = unsafe.Pointer(&adddmi_args.arg_cz)
	adddmi_args.argptr[14] = unsafe.Pointer(&adddmi_args.arg_Nx)
	adddmi_args.argptr[15] = unsafe.Pointer(&adddmi_args.arg_Ny)
	adddmi_args.argptr[16] = unsafe.Pointer(&adddmi_args.arg_Nz)
	adddmi_args.argptr[17] = unsafe.Pointer(&adddmi_args.arg_PBC)
	adddmi_args.argptr[18] = unsafe.Pointer(&adddmi_args.arg_OpenBC)
}

// Wrapper for adddmi OpenCL kernel, asynchronous.
func k_adddmi_async(Hx unsafe.Pointer, Hy unsafe.Pointer, Hz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, Ms_ unsafe.Pointer, Ms_mul float32, aLUT2d unsafe.Pointer, dLUT2d unsafe.Pointer, regions unsafe.Pointer, cx float32, cy float32, cz float32, Nx int, Ny int, Nz int, PBC uint8, OpenBC uint8, cfg *config, events []*cl.Event, launchQueue *cl.CommandQueue) *cl.Event {
	if Synchronous { // debug
		launchQueue.Finish()
		timer.Start("adddmi")
	}

	adddmi_args.Lock()
	defer adddmi_args.Unlock()

	adddmi_args.arg_Hx = Hx
	adddmi_args.arg_Hy = Hy
	adddmi_args.arg_Hz = Hz
	adddmi_args.arg_mx = mx
	adddmi_args.arg_my = my
	adddmi_args.arg_mz = mz
	adddmi_args.arg_Ms_ = Ms_
	adddmi_args.arg_Ms_mul = Ms_mul
	adddmi_args.arg_aLUT2d = aLUT2d
	adddmi_args.arg_dLUT2d = dLUT2d
	adddmi_args.arg_regions = regions
	adddmi_args.arg_cx = cx
	adddmi_args.arg_cy = cy
	adddmi_args.arg_cz = cz
	adddmi_args.arg_Nx = Nx
	adddmi_args.arg_Ny = Ny
	adddmi_args.arg_Nz = Nz
	adddmi_args.arg_PBC = PBC
	adddmi_args.arg_OpenBC = OpenBC

	SetKernelArgWrapper("adddmi", 0, Hx)
	SetKernelArgWrapper("adddmi", 1, Hy)
	SetKernelArgWrapper("adddmi", 2, Hz)
	SetKernelArgWrapper("adddmi", 3, mx)
	SetKernelArgWrapper("adddmi", 4, my)
	SetKernelArgWrapper("adddmi", 5, mz)
	SetKernelArgWrapper("adddmi", 6, Ms_)
	SetKernelArgWrapper("adddmi", 7, Ms_mul)
	SetKernelArgWrapper("adddmi", 8, aLUT2d)
	SetKernelArgWrapper("adddmi", 9, dLUT2d)
	SetKernelArgWrapper("adddmi", 10, regions)
	SetKernelArgWrapper("adddmi", 11, cx)
	SetKernelArgWrapper("adddmi", 12, cy)
	SetKernelArgWrapper("adddmi", 13, cz)
	SetKernelArgWrapper("adddmi", 14, Nx)
	SetKernelArgWrapper("adddmi", 15, Ny)
	SetKernelArgWrapper("adddmi", 16, Nz)
	SetKernelArgWrapper("adddmi", 17, PBC)
	SetKernelArgWrapper("adddmi", 18, OpenBC)

	//	args := adddmi_args.argptr[:]
	event := LaunchKernel("adddmi", cfg.Grid, cfg.Block, launchQueue, events)

	if Synchronous { // debug
		launchQueue.Finish()
		timer.Stop("adddmi")
	}

	return event
}
