package opencl

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for llnoprecess kernel invocation
type llnoprecess_args_t struct {
	arg_tx unsafe.Pointer
	arg_ty unsafe.Pointer
	arg_tz unsafe.Pointer
	arg_mx unsafe.Pointer
	arg_my unsafe.Pointer
	arg_mz unsafe.Pointer
	arg_hx unsafe.Pointer
	arg_hy unsafe.Pointer
	arg_hz unsafe.Pointer
	arg_N  int
	argptr [10]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for llnoprecess kernel invocation
var llnoprecess_args llnoprecess_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	llnoprecess_args.argptr[0] = unsafe.Pointer(&llnoprecess_args.arg_tx)
	llnoprecess_args.argptr[1] = unsafe.Pointer(&llnoprecess_args.arg_ty)
	llnoprecess_args.argptr[2] = unsafe.Pointer(&llnoprecess_args.arg_tz)
	llnoprecess_args.argptr[3] = unsafe.Pointer(&llnoprecess_args.arg_mx)
	llnoprecess_args.argptr[4] = unsafe.Pointer(&llnoprecess_args.arg_my)
	llnoprecess_args.argptr[5] = unsafe.Pointer(&llnoprecess_args.arg_mz)
	llnoprecess_args.argptr[6] = unsafe.Pointer(&llnoprecess_args.arg_hx)
	llnoprecess_args.argptr[7] = unsafe.Pointer(&llnoprecess_args.arg_hy)
	llnoprecess_args.argptr[8] = unsafe.Pointer(&llnoprecess_args.arg_hz)
	llnoprecess_args.argptr[9] = unsafe.Pointer(&llnoprecess_args.arg_N)
}

// Wrapper for llnoprecess OpenCL kernel, asynchronous.
func k_llnoprecess_async(tx unsafe.Pointer, ty unsafe.Pointer, tz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, hx unsafe.Pointer, hy unsafe.Pointer, hz unsafe.Pointer, N int, cfg *config, events []*cl.Event, launchQueue *cl.CommandQueue) *cl.Event {
	if Synchronous { // debug
		launchQueue.Finish()
		timer.Start("llnoprecess")
	}

	llnoprecess_args.Lock()
	defer llnoprecess_args.Unlock()

	llnoprecess_args.arg_tx = tx
	llnoprecess_args.arg_ty = ty
	llnoprecess_args.arg_tz = tz
	llnoprecess_args.arg_mx = mx
	llnoprecess_args.arg_my = my
	llnoprecess_args.arg_mz = mz
	llnoprecess_args.arg_hx = hx
	llnoprecess_args.arg_hy = hy
	llnoprecess_args.arg_hz = hz
	llnoprecess_args.arg_N = N

	SetKernelArgWrapper("llnoprecess", 0, tx)
	SetKernelArgWrapper("llnoprecess", 1, ty)
	SetKernelArgWrapper("llnoprecess", 2, tz)
	SetKernelArgWrapper("llnoprecess", 3, mx)
	SetKernelArgWrapper("llnoprecess", 4, my)
	SetKernelArgWrapper("llnoprecess", 5, mz)
	SetKernelArgWrapper("llnoprecess", 6, hx)
	SetKernelArgWrapper("llnoprecess", 7, hy)
	SetKernelArgWrapper("llnoprecess", 8, hz)
	SetKernelArgWrapper("llnoprecess", 9, N)

	//	args := llnoprecess_args.argptr[:]
	event := LaunchKernel("llnoprecess", cfg.Grid, cfg.Block, launchQueue, events)

	if Synchronous { // debug
		launchQueue.Finish()
		timer.Stop("llnoprecess")
	}

	return event
}
