package opencl

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for madd6 kernel invocation
type madd6_args_t struct {
	arg_dst  unsafe.Pointer
	arg_src1 unsafe.Pointer
	arg_fac1 float32
	arg_src2 unsafe.Pointer
	arg_fac2 float32
	arg_src3 unsafe.Pointer
	arg_fac3 float32
	arg_src4 unsafe.Pointer
	arg_fac4 float32
	arg_src5 unsafe.Pointer
	arg_fac5 float32
	arg_src6 unsafe.Pointer
	arg_fac6 float32
	arg_N    int
	argptr   [14]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for madd6 kernel invocation
var madd6_args madd6_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	madd6_args.argptr[0] = unsafe.Pointer(&madd6_args.arg_dst)
	madd6_args.argptr[1] = unsafe.Pointer(&madd6_args.arg_src1)
	madd6_args.argptr[2] = unsafe.Pointer(&madd6_args.arg_fac1)
	madd6_args.argptr[3] = unsafe.Pointer(&madd6_args.arg_src2)
	madd6_args.argptr[4] = unsafe.Pointer(&madd6_args.arg_fac2)
	madd6_args.argptr[5] = unsafe.Pointer(&madd6_args.arg_src3)
	madd6_args.argptr[6] = unsafe.Pointer(&madd6_args.arg_fac3)
	madd6_args.argptr[7] = unsafe.Pointer(&madd6_args.arg_src4)
	madd6_args.argptr[8] = unsafe.Pointer(&madd6_args.arg_fac4)
	madd6_args.argptr[9] = unsafe.Pointer(&madd6_args.arg_src5)
	madd6_args.argptr[10] = unsafe.Pointer(&madd6_args.arg_fac5)
	madd6_args.argptr[11] = unsafe.Pointer(&madd6_args.arg_src6)
	madd6_args.argptr[12] = unsafe.Pointer(&madd6_args.arg_fac6)
	madd6_args.argptr[13] = unsafe.Pointer(&madd6_args.arg_N)
}

// Wrapper for madd6 OpenCL kernel, asynchronous.
func k_madd6_async(dst unsafe.Pointer, src1 unsafe.Pointer, fac1 float32, src2 unsafe.Pointer, fac2 float32, src3 unsafe.Pointer, fac3 float32, src4 unsafe.Pointer, fac4 float32, src5 unsafe.Pointer, fac5 float32, src6 unsafe.Pointer, fac6 float32, N int, cfg *config, events []*cl.Event, launchQueue *cl.CommandQueue) *cl.Event {
	if Synchronous { // debug
		launchQueue.Finish()
		timer.Start("madd6")
	}

	madd6_args.Lock()
	defer madd6_args.Unlock()

	madd6_args.arg_dst = dst
	madd6_args.arg_src1 = src1
	madd6_args.arg_fac1 = fac1
	madd6_args.arg_src2 = src2
	madd6_args.arg_fac2 = fac2
	madd6_args.arg_src3 = src3
	madd6_args.arg_fac3 = fac3
	madd6_args.arg_src4 = src4
	madd6_args.arg_fac4 = fac4
	madd6_args.arg_src5 = src5
	madd6_args.arg_fac5 = fac5
	madd6_args.arg_src6 = src6
	madd6_args.arg_fac6 = fac6
	madd6_args.arg_N = N

	SetKernelArgWrapper("madd6", 0, dst)
	SetKernelArgWrapper("madd6", 1, src1)
	SetKernelArgWrapper("madd6", 2, fac1)
	SetKernelArgWrapper("madd6", 3, src2)
	SetKernelArgWrapper("madd6", 4, fac2)
	SetKernelArgWrapper("madd6", 5, src3)
	SetKernelArgWrapper("madd6", 6, fac3)
	SetKernelArgWrapper("madd6", 7, src4)
	SetKernelArgWrapper("madd6", 8, fac4)
	SetKernelArgWrapper("madd6", 9, src5)
	SetKernelArgWrapper("madd6", 10, fac5)
	SetKernelArgWrapper("madd6", 11, src6)
	SetKernelArgWrapper("madd6", 12, fac6)
	SetKernelArgWrapper("madd6", 13, N)

	//	args := madd6_args.argptr[:]
	event := LaunchKernel("madd6", cfg.Grid, cfg.Block, launchQueue, events)

	if Synchronous { // debug
		launchQueue.Finish()
		timer.Stop("madd6")
	}

	return event
}
