package opencl

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for madd2 kernel invocation
type madd2_args_t struct {
	arg_dst  unsafe.Pointer
	arg_src1 unsafe.Pointer
	arg_fac1 float32
	arg_src2 unsafe.Pointer
	arg_fac2 float32
	arg_N    int
	argptr   [6]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for madd2 kernel invocation
var madd2_args madd2_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	madd2_args.argptr[0] = unsafe.Pointer(&madd2_args.arg_dst)
	madd2_args.argptr[1] = unsafe.Pointer(&madd2_args.arg_src1)
	madd2_args.argptr[2] = unsafe.Pointer(&madd2_args.arg_fac1)
	madd2_args.argptr[3] = unsafe.Pointer(&madd2_args.arg_src2)
	madd2_args.argptr[4] = unsafe.Pointer(&madd2_args.arg_fac2)
	madd2_args.argptr[5] = unsafe.Pointer(&madd2_args.arg_N)
}

// Wrapper for madd2 OpenCL kernel, asynchronous.
func k_madd2_async(dst unsafe.Pointer, src1 unsafe.Pointer, fac1 float32, src2 unsafe.Pointer, fac2 float32, N int, cfg *config, events []*cl.Event, launchQueue *cl.CommandQueue) *cl.Event {
	if Synchronous { // debug
		launchQueue.Finish()
		timer.Start("madd2")
	}

	madd2_args.Lock()
	defer madd2_args.Unlock()

	madd2_args.arg_dst = dst
	madd2_args.arg_src1 = src1
	madd2_args.arg_fac1 = fac1
	madd2_args.arg_src2 = src2
	madd2_args.arg_fac2 = fac2
	madd2_args.arg_N = N

	SetKernelArgWrapper("madd2", 0, dst)
	SetKernelArgWrapper("madd2", 1, src1)
	SetKernelArgWrapper("madd2", 2, fac1)
	SetKernelArgWrapper("madd2", 3, src2)
	SetKernelArgWrapper("madd2", 4, fac2)
	SetKernelArgWrapper("madd2", 5, N)

	//	args := madd2_args.argptr[:]
	event := LaunchKernel("madd2", cfg.Grid, cfg.Block, launchQueue, events)

	if Synchronous { // debug
		launchQueue.Finish()
		timer.Stop("madd2")
	}

	return event
}
