package opencl

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for madd5 kernel invocation
type madd5_args_t struct {
	arg_dst  unsafe.Pointer
	arg_src1 unsafe.Pointer
	arg_fac1 float32
	arg_src2 unsafe.Pointer
	arg_fac2 float32
	arg_src3 unsafe.Pointer
	arg_fac3 float32
	arg_src4 unsafe.Pointer
	arg_fac4 float32
	arg_src5 unsafe.Pointer
	arg_fac5 float32
	arg_N    int
	argptr   [12]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for madd5 kernel invocation
var madd5_args madd5_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	madd5_args.argptr[0] = unsafe.Pointer(&madd5_args.arg_dst)
	madd5_args.argptr[1] = unsafe.Pointer(&madd5_args.arg_src1)
	madd5_args.argptr[2] = unsafe.Pointer(&madd5_args.arg_fac1)
	madd5_args.argptr[3] = unsafe.Pointer(&madd5_args.arg_src2)
	madd5_args.argptr[4] = unsafe.Pointer(&madd5_args.arg_fac2)
	madd5_args.argptr[5] = unsafe.Pointer(&madd5_args.arg_src3)
	madd5_args.argptr[6] = unsafe.Pointer(&madd5_args.arg_fac3)
	madd5_args.argptr[7] = unsafe.Pointer(&madd5_args.arg_src4)
	madd5_args.argptr[8] = unsafe.Pointer(&madd5_args.arg_fac4)
	madd5_args.argptr[9] = unsafe.Pointer(&madd5_args.arg_src5)
	madd5_args.argptr[10] = unsafe.Pointer(&madd5_args.arg_fac5)
	madd5_args.argptr[11] = unsafe.Pointer(&madd5_args.arg_N)
}

// Wrapper for madd5 OpenCL kernel, asynchronous.
func k_madd5_async(dst unsafe.Pointer, src1 unsafe.Pointer, fac1 float32, src2 unsafe.Pointer, fac2 float32, src3 unsafe.Pointer, fac3 float32, src4 unsafe.Pointer, fac4 float32, src5 unsafe.Pointer, fac5 float32, N int, cfg *config, events []*cl.Event, launchQueue *cl.CommandQueue) *cl.Event {
	if Synchronous { // debug
		launchQueue.Finish()
		timer.Start("madd5")
	}

	madd5_args.Lock()
	defer madd5_args.Unlock()

	madd5_args.arg_dst = dst
	madd5_args.arg_src1 = src1
	madd5_args.arg_fac1 = fac1
	madd5_args.arg_src2 = src2
	madd5_args.arg_fac2 = fac2
	madd5_args.arg_src3 = src3
	madd5_args.arg_fac3 = fac3
	madd5_args.arg_src4 = src4
	madd5_args.arg_fac4 = fac4
	madd5_args.arg_src5 = src5
	madd5_args.arg_fac5 = fac5
	madd5_args.arg_N = N

	SetKernelArgWrapper("madd5", 0, dst)
	SetKernelArgWrapper("madd5", 1, src1)
	SetKernelArgWrapper("madd5", 2, fac1)
	SetKernelArgWrapper("madd5", 3, src2)
	SetKernelArgWrapper("madd5", 4, fac2)
	SetKernelArgWrapper("madd5", 5, src3)
	SetKernelArgWrapper("madd5", 6, fac3)
	SetKernelArgWrapper("madd5", 7, src4)
	SetKernelArgWrapper("madd5", 8, fac4)
	SetKernelArgWrapper("madd5", 9, src5)
	SetKernelArgWrapper("madd5", 10, fac5)
	SetKernelArgWrapper("madd5", 11, N)

	//	args := madd5_args.argptr[:]
	event := LaunchKernel("madd5", cfg.Grid, cfg.Block, launchQueue, events)

	if Synchronous { // debug
		launchQueue.Finish()
		timer.Stop("madd5")
	}

	return event
}
