package opencl

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for madd3 kernel invocation
type madd3_args_t struct {
	arg_dst  unsafe.Pointer
	arg_src1 unsafe.Pointer
	arg_fac1 float32
	arg_src2 unsafe.Pointer
	arg_fac2 float32
	arg_src3 unsafe.Pointer
	arg_fac3 float32
	arg_N    int
	argptr   [8]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for madd3 kernel invocation
var madd3_args madd3_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	madd3_args.argptr[0] = unsafe.Pointer(&madd3_args.arg_dst)
	madd3_args.argptr[1] = unsafe.Pointer(&madd3_args.arg_src1)
	madd3_args.argptr[2] = unsafe.Pointer(&madd3_args.arg_fac1)
	madd3_args.argptr[3] = unsafe.Pointer(&madd3_args.arg_src2)
	madd3_args.argptr[4] = unsafe.Pointer(&madd3_args.arg_fac2)
	madd3_args.argptr[5] = unsafe.Pointer(&madd3_args.arg_src3)
	madd3_args.argptr[6] = unsafe.Pointer(&madd3_args.arg_fac3)
	madd3_args.argptr[7] = unsafe.Pointer(&madd3_args.arg_N)
}

// Wrapper for madd3 OpenCL kernel, asynchronous.
func k_madd3_async(dst unsafe.Pointer, src1 unsafe.Pointer, fac1 float32, src2 unsafe.Pointer, fac2 float32, src3 unsafe.Pointer, fac3 float32, N int, cfg *config, events []*cl.Event, launchQueue *cl.CommandQueue) *cl.Event {
	if Synchronous { // debug
		launchQueue.Finish()
		timer.Start("madd3")
	}

	madd3_args.Lock()
	defer madd3_args.Unlock()

	madd3_args.arg_dst = dst
	madd3_args.arg_src1 = src1
	madd3_args.arg_fac1 = fac1
	madd3_args.arg_src2 = src2
	madd3_args.arg_fac2 = fac2
	madd3_args.arg_src3 = src3
	madd3_args.arg_fac3 = fac3
	madd3_args.arg_N = N

	SetKernelArgWrapper("madd3", 0, dst)
	SetKernelArgWrapper("madd3", 1, src1)
	SetKernelArgWrapper("madd3", 2, fac1)
	SetKernelArgWrapper("madd3", 3, src2)
	SetKernelArgWrapper("madd3", 4, fac2)
	SetKernelArgWrapper("madd3", 5, src3)
	SetKernelArgWrapper("madd3", 6, fac3)
	SetKernelArgWrapper("madd3", 7, N)

	//	args := madd3_args.argptr[:]
	event := LaunchKernel("madd3", cfg.Grid, cfg.Block, launchQueue, events)

	if Synchronous { // debug
		launchQueue.Finish()
		timer.Stop("madd3")
	}

	return event
}
