package opencl

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for regiondecode kernel invocation
type regiondecode_args_t struct {
	arg_dst     unsafe.Pointer
	arg_LUT     unsafe.Pointer
	arg_regions unsafe.Pointer
	arg_N       int
	argptr      [4]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for regiondecode kernel invocation
var regiondecode_args regiondecode_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	regiondecode_args.argptr[0] = unsafe.Pointer(&regiondecode_args.arg_dst)
	regiondecode_args.argptr[1] = unsafe.Pointer(&regiondecode_args.arg_LUT)
	regiondecode_args.argptr[2] = unsafe.Pointer(&regiondecode_args.arg_regions)
	regiondecode_args.argptr[3] = unsafe.Pointer(&regiondecode_args.arg_N)
}

// Wrapper for regiondecode OpenCL kernel, asynchronous.
func k_regiondecode_async(dst unsafe.Pointer, LUT unsafe.Pointer, regions unsafe.Pointer, N int, cfg *config, events []*cl.Event, launchQueue *cl.CommandQueue) *cl.Event {
	if Synchronous { // debug
		launchQueue.Finish()
		timer.Start("regiondecode")
	}

	regiondecode_args.Lock()
	defer regiondecode_args.Unlock()

	regiondecode_args.arg_dst = dst
	regiondecode_args.arg_LUT = LUT
	regiondecode_args.arg_regions = regions
	regiondecode_args.arg_N = N

	SetKernelArgWrapper("regiondecode", 0, dst)
	SetKernelArgWrapper("regiondecode", 1, LUT)
	SetKernelArgWrapper("regiondecode", 2, regions)
	SetKernelArgWrapper("regiondecode", 3, N)

	//	args := regiondecode_args.argptr[:]
	event := LaunchKernel("regiondecode", cfg.Grid, cfg.Block, launchQueue, events)

	if Synchronous { // debug
		launchQueue.Finish()
		timer.Stop("regiondecode")
	}

	return event
}
