package opencl

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for shiftx kernel invocation
type shiftx_args_t struct {
	arg_dst    unsafe.Pointer
	arg_src    unsafe.Pointer
	arg_Nx     int
	arg_Ny     int
	arg_Nz     int
	arg_shx    int
	arg_clampL float32
	arg_clampR float32
	argptr     [8]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for shiftx kernel invocation
var shiftx_args shiftx_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	shiftx_args.argptr[0] = unsafe.Pointer(&shiftx_args.arg_dst)
	shiftx_args.argptr[1] = unsafe.Pointer(&shiftx_args.arg_src)
	shiftx_args.argptr[2] = unsafe.Pointer(&shiftx_args.arg_Nx)
	shiftx_args.argptr[3] = unsafe.Pointer(&shiftx_args.arg_Ny)
	shiftx_args.argptr[4] = unsafe.Pointer(&shiftx_args.arg_Nz)
	shiftx_args.argptr[5] = unsafe.Pointer(&shiftx_args.arg_shx)
	shiftx_args.argptr[6] = unsafe.Pointer(&shiftx_args.arg_clampL)
	shiftx_args.argptr[7] = unsafe.Pointer(&shiftx_args.arg_clampR)
}

// Wrapper for shiftx OpenCL kernel, asynchronous.
func k_shiftx_async(dst unsafe.Pointer, src unsafe.Pointer, Nx int, Ny int, Nz int, shx int, clampL float32, clampR float32, cfg *config, events []*cl.Event, launchQueue *cl.CommandQueue) *cl.Event {
	if Synchronous { // debug
		launchQueue.Finish()
		timer.Start("shiftx")
	}

	shiftx_args.Lock()
	defer shiftx_args.Unlock()

	shiftx_args.arg_dst = dst
	shiftx_args.arg_src = src
	shiftx_args.arg_Nx = Nx
	shiftx_args.arg_Ny = Ny
	shiftx_args.arg_Nz = Nz
	shiftx_args.arg_shx = shx
	shiftx_args.arg_clampL = clampL
	shiftx_args.arg_clampR = clampR

	SetKernelArgWrapper("shiftx", 0, dst)
	SetKernelArgWrapper("shiftx", 1, src)
	SetKernelArgWrapper("shiftx", 2, Nx)
	SetKernelArgWrapper("shiftx", 3, Ny)
	SetKernelArgWrapper("shiftx", 4, Nz)
	SetKernelArgWrapper("shiftx", 5, shx)
	SetKernelArgWrapper("shiftx", 6, clampL)
	SetKernelArgWrapper("shiftx", 7, clampR)

	//	args := shiftx_args.argptr[:]
	event := LaunchKernel("shiftx", cfg.Grid, cfg.Block, launchQueue, events)

	if Synchronous { // debug
		launchQueue.Finish()
		timer.Stop("shiftx")
	}

	return event
}
