package opencl

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for shiftbytesy kernel invocation
type shiftbytesy_args_t struct {
	arg_dst    unsafe.Pointer
	arg_src    unsafe.Pointer
	arg_Nx     int
	arg_Ny     int
	arg_Nz     int
	arg_shy    int
	arg_clampV uint8
	argptr     [7]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for shiftbytesy kernel invocation
var shiftbytesy_args shiftbytesy_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	shiftbytesy_args.argptr[0] = unsafe.Pointer(&shiftbytesy_args.arg_dst)
	shiftbytesy_args.argptr[1] = unsafe.Pointer(&shiftbytesy_args.arg_src)
	shiftbytesy_args.argptr[2] = unsafe.Pointer(&shiftbytesy_args.arg_Nx)
	shiftbytesy_args.argptr[3] = unsafe.Pointer(&shiftbytesy_args.arg_Ny)
	shiftbytesy_args.argptr[4] = unsafe.Pointer(&shiftbytesy_args.arg_Nz)
	shiftbytesy_args.argptr[5] = unsafe.Pointer(&shiftbytesy_args.arg_shy)
	shiftbytesy_args.argptr[6] = unsafe.Pointer(&shiftbytesy_args.arg_clampV)
}

// Wrapper for shiftbytesy OpenCL kernel, asynchronous.
func k_shiftbytesy_async(dst unsafe.Pointer, src unsafe.Pointer, Nx int, Ny int, Nz int, shy int, clampV uint8, cfg *config, events []*cl.Event, launchQueue *cl.CommandQueue) *cl.Event {
	if Synchronous { // debug
		launchQueue.Finish()
		timer.Start("shiftbytesy")
	}

	shiftbytesy_args.Lock()
	defer shiftbytesy_args.Unlock()

	shiftbytesy_args.arg_dst = dst
	shiftbytesy_args.arg_src = src
	shiftbytesy_args.arg_Nx = Nx
	shiftbytesy_args.arg_Ny = Ny
	shiftbytesy_args.arg_Nz = Nz
	shiftbytesy_args.arg_shy = shy
	shiftbytesy_args.arg_clampV = clampV

	SetKernelArgWrapper("shiftbytesy", 0, dst)
	SetKernelArgWrapper("shiftbytesy", 1, src)
	SetKernelArgWrapper("shiftbytesy", 2, Nx)
	SetKernelArgWrapper("shiftbytesy", 3, Ny)
	SetKernelArgWrapper("shiftbytesy", 4, Nz)
	SetKernelArgWrapper("shiftbytesy", 5, shy)
	SetKernelArgWrapper("shiftbytesy", 6, clampV)

	//	args := shiftbytesy_args.argptr[:]
	event := LaunchKernel("shiftbytesy", cfg.Grid, cfg.Block, launchQueue, events)

	if Synchronous { // debug
		launchQueue.Finish()
		timer.Stop("shiftbytesy")
	}

	return event
}
