package opencl

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for tworegionexchange_field kernel invocation
type tworegionexchange_field_args_t struct {
	arg_Bx       unsafe.Pointer
	arg_By       unsafe.Pointer
	arg_Bz       unsafe.Pointer
	arg_mx       unsafe.Pointer
	arg_my       unsafe.Pointer
	arg_mz       unsafe.Pointer
	arg_Ms_      unsafe.Pointer
	arg_Ms_mul   float32
	arg_regions  unsafe.Pointer
	arg_regionA  uint8
	arg_regionB  uint8
	arg_strideX  int
	arg_strideY  int
	arg_strideZ  int
	arg_sig_eff  float32
	arg_sig2_eff float32
	arg_Nx       int
	arg_Ny       int
	arg_Nz       int
	argptr       [19]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for tworegionexchange_field kernel invocation
var tworegionexchange_field_args tworegionexchange_field_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	tworegionexchange_field_args.argptr[0] = unsafe.Pointer(&tworegionexchange_field_args.arg_Bx)
	tworegionexchange_field_args.argptr[1] = unsafe.Pointer(&tworegionexchange_field_args.arg_By)
	tworegionexchange_field_args.argptr[2] = unsafe.Pointer(&tworegionexchange_field_args.arg_Bz)
	tworegionexchange_field_args.argptr[3] = unsafe.Pointer(&tworegionexchange_field_args.arg_mx)
	tworegionexchange_field_args.argptr[4] = unsafe.Pointer(&tworegionexchange_field_args.arg_my)
	tworegionexchange_field_args.argptr[5] = unsafe.Pointer(&tworegionexchange_field_args.arg_mz)
	tworegionexchange_field_args.argptr[6] = unsafe.Pointer(&tworegionexchange_field_args.arg_Ms_)
	tworegionexchange_field_args.argptr[7] = unsafe.Pointer(&tworegionexchange_field_args.arg_Ms_mul)
	tworegionexchange_field_args.argptr[8] = unsafe.Pointer(&tworegionexchange_field_args.arg_regions)
	tworegionexchange_field_args.argptr[9] = unsafe.Pointer(&tworegionexchange_field_args.arg_regionA)
	tworegionexchange_field_args.argptr[10] = unsafe.Pointer(&tworegionexchange_field_args.arg_regionB)
	tworegionexchange_field_args.argptr[11] = unsafe.Pointer(&tworegionexchange_field_args.arg_strideX)
	tworegionexchange_field_args.argptr[12] = unsafe.Pointer(&tworegionexchange_field_args.arg_strideY)
	tworegionexchange_field_args.argptr[13] = unsafe.Pointer(&tworegionexchange_field_args.arg_strideZ)
	tworegionexchange_field_args.argptr[14] = unsafe.Pointer(&tworegionexchange_field_args.arg_sig_eff)
	tworegionexchange_field_args.argptr[15] = unsafe.Pointer(&tworegionexchange_field_args.arg_sig2_eff)
	tworegionexchange_field_args.argptr[16] = unsafe.Pointer(&tworegionexchange_field_args.arg_Nx)
	tworegionexchange_field_args.argptr[17] = unsafe.Pointer(&tworegionexchange_field_args.arg_Ny)
	tworegionexchange_field_args.argptr[18] = unsafe.Pointer(&tworegionexchange_field_args.arg_Nz)
}

// Wrapper for tworegionexchange_field OpenCL kernel, asynchronous.
func k_tworegionexchange_field_async(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, Ms_ unsafe.Pointer, Ms_mul float32, regions unsafe.Pointer, regionA uint8, regionB uint8, strideX int, strideY int, strideZ int, sig_eff float32, sig2_eff float32, Nx int, Ny int, Nz int, cfg *config, events []*cl.Event, launchQueue *cl.CommandQueue) *cl.Event {
	if Synchronous { // debug
		launchQueue.Finish()
		timer.Start("tworegionexchange_field")
	}

	tworegionexchange_field_args.Lock()
	defer tworegionexchange_field_args.Unlock()

	tworegionexchange_field_args.arg_Bx = Bx
	tworegionexchange_field_args.arg_By = By
	tworegionexchange_field_args.arg_Bz = Bz
	tworegionexchange_field_args.arg_mx = mx
	tworegionexchange_field_args.arg_my = my
	tworegionexchange_field_args.arg_mz = mz
	tworegionexchange_field_args.arg_Ms_ = Ms_
	tworegionexchange_field_args.arg_Ms_mul = Ms_mul
	tworegionexchange_field_args.arg_regions = regions
	tworegionexchange_field_args.arg_regionA = regionA
	tworegionexchange_field_args.arg_regionB = regionB
	tworegionexchange_field_args.arg_strideX = strideX
	tworegionexchange_field_args.arg_strideY = strideY
	tworegionexchange_field_args.arg_strideZ = strideZ
	tworegionexchange_field_args.arg_sig_eff = sig_eff
	tworegionexchange_field_args.arg_sig2_eff = sig2_eff
	tworegionexchange_field_args.arg_Nx = Nx
	tworegionexchange_field_args.arg_Ny = Ny
	tworegionexchange_field_args.arg_Nz = Nz

	SetKernelArgWrapper("tworegionexchange_field", 0, Bx)
	SetKernelArgWrapper("tworegionexchange_field", 1, By)
	SetKernelArgWrapper("tworegionexchange_field", 2, Bz)
	SetKernelArgWrapper("tworegionexchange_field", 3, mx)
	SetKernelArgWrapper("tworegionexchange_field", 4, my)
	SetKernelArgWrapper("tworegionexchange_field", 5, mz)
	SetKernelArgWrapper("tworegionexchange_field", 6, Ms_)
	SetKernelArgWrapper("tworegionexchange_field", 7, Ms_mul)
	SetKernelArgWrapper("tworegionexchange_field", 8, regions)
	SetKernelArgWrapper("tworegionexchange_field", 9, regionA)
	SetKernelArgWrapper("tworegionexchange_field", 10, regionB)
	SetKernelArgWrapper("tworegionexchange_field", 11, strideX)
	SetKernelArgWrapper("tworegionexchange_field", 12, strideY)
	SetKernelArgWrapper("tworegionexchange_field", 13, strideZ)
	SetKernelArgWrapper("tworegionexchange_field", 14, sig_eff)
	SetKernelArgWrapper("tworegionexchange_field", 15, sig2_eff)
	SetKernelArgWrapper("tworegionexchange_field", 16, Nx)
	SetKernelArgWrapper("tworegionexchange_field", 17, Ny)
	SetKernelArgWrapper("tworegionexchange_field", 18, Nz)

	//	args := tworegionexchange_field_args.argptr[:]
	event := LaunchKernel("tworegionexchange_field", cfg.Grid, cfg.Block, launchQueue, events)

	if Synchronous { // debug
		launchQueue.Finish()
		timer.Stop("tworegionexchange_field")
	}

	return event
}
