package oclRAND

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for mtgp32_init_seed_kernel kernel invocation
type mtgp32_init_seed_kernel_args_t struct {
	arg_param_tbl         unsafe.Pointer
	arg_temper_tbl        unsafe.Pointer
	arg_single_temper_tbl unsafe.Pointer
	arg_pos_tbl           unsafe.Pointer
	arg_sh1_tbl           unsafe.Pointer
	arg_sh2_tbl           unsafe.Pointer
	arg_d_status          unsafe.Pointer
	arg_seed              unsafe.Pointer
	argptr                [8]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for mtgp32_init_seed_kernel kernel invocation
var mtgp32_init_seed_kernel_args mtgp32_init_seed_kernel_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	mtgp32_init_seed_kernel_args.argptr[0] = unsafe.Pointer(&mtgp32_init_seed_kernel_args.arg_param_tbl)
	mtgp32_init_seed_kernel_args.argptr[1] = unsafe.Pointer(&mtgp32_init_seed_kernel_args.arg_temper_tbl)
	mtgp32_init_seed_kernel_args.argptr[2] = unsafe.Pointer(&mtgp32_init_seed_kernel_args.arg_single_temper_tbl)
	mtgp32_init_seed_kernel_args.argptr[3] = unsafe.Pointer(&mtgp32_init_seed_kernel_args.arg_pos_tbl)
	mtgp32_init_seed_kernel_args.argptr[4] = unsafe.Pointer(&mtgp32_init_seed_kernel_args.arg_sh1_tbl)
	mtgp32_init_seed_kernel_args.argptr[5] = unsafe.Pointer(&mtgp32_init_seed_kernel_args.arg_sh2_tbl)
	mtgp32_init_seed_kernel_args.argptr[6] = unsafe.Pointer(&mtgp32_init_seed_kernel_args.arg_d_status)
	mtgp32_init_seed_kernel_args.argptr[7] = unsafe.Pointer(&mtgp32_init_seed_kernel_args.arg_seed)
}

// Wrapper for mtgp32_init_seed_kernel OpenCL kernel, asynchronous.
func k_mtgp32_init_seed_kernel_async(param_tbl unsafe.Pointer, temper_tbl unsafe.Pointer, single_temper_tbl unsafe.Pointer, pos_tbl unsafe.Pointer, sh1_tbl unsafe.Pointer, sh2_tbl unsafe.Pointer, d_status unsafe.Pointer, seed unsafe.Pointer, cfg *config, events []*cl.Event) *cl.Event {
	if Synchronous { // debug
		ClCmdQueue.Finish()
		timer.Start("mtgp32_init_seed_kernel")
	}

	mtgp32_init_seed_kernel_args.Lock()
	defer mtgp32_init_seed_kernel_args.Unlock()

	mtgp32_init_seed_kernel_args.arg_param_tbl = param_tbl
	mtgp32_init_seed_kernel_args.arg_temper_tbl = temper_tbl
	mtgp32_init_seed_kernel_args.arg_single_temper_tbl = single_temper_tbl
	mtgp32_init_seed_kernel_args.arg_pos_tbl = pos_tbl
	mtgp32_init_seed_kernel_args.arg_sh1_tbl = sh1_tbl
	mtgp32_init_seed_kernel_args.arg_sh2_tbl = sh2_tbl
	mtgp32_init_seed_kernel_args.arg_d_status = d_status
	mtgp32_init_seed_kernel_args.arg_seed = seed

	SetKernelArgWrapper("mtgp32_init_seed_kernel", 0, param_tbl)
	SetKernelArgWrapper("mtgp32_init_seed_kernel", 1, temper_tbl)
	SetKernelArgWrapper("mtgp32_init_seed_kernel", 2, single_temper_tbl)
	SetKernelArgWrapper("mtgp32_init_seed_kernel", 3, pos_tbl)
	SetKernelArgWrapper("mtgp32_init_seed_kernel", 4, sh1_tbl)
	SetKernelArgWrapper("mtgp32_init_seed_kernel", 5, sh2_tbl)
	SetKernelArgWrapper("mtgp32_init_seed_kernel", 6, d_status)
	SetKernelArgWrapper("mtgp32_init_seed_kernel", 7, seed)

	//	args := mtgp32_init_seed_kernel_args.argptr[:]
	event := LaunchKernel("mtgp32_init_seed_kernel", cfg.Grid, cfg.Block, events)

	if Synchronous { // debug
		ClCmdQueue.Finish()
		timer.Stop("mtgp32_init_seed_kernel")
	}

	return event
}
