package oclRAND

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for threefry_seed kernel invocation
type threefry_seed_args_t struct {
	arg_state_key     unsafe.Pointer
	arg_state_counter unsafe.Pointer
	arg_state_result  unsafe.Pointer
	arg_state_tracker unsafe.Pointer
	arg_seed          unsafe.Pointer
	argptr            [5]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for threefry_seed kernel invocation
var threefry_seed_args threefry_seed_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	threefry_seed_args.argptr[0] = unsafe.Pointer(&threefry_seed_args.arg_state_key)
	threefry_seed_args.argptr[1] = unsafe.Pointer(&threefry_seed_args.arg_state_counter)
	threefry_seed_args.argptr[2] = unsafe.Pointer(&threefry_seed_args.arg_state_result)
	threefry_seed_args.argptr[3] = unsafe.Pointer(&threefry_seed_args.arg_state_tracker)
	threefry_seed_args.argptr[4] = unsafe.Pointer(&threefry_seed_args.arg_seed)
}

// Wrapper for threefry_seed OpenCL kernel, asynchronous.
func k_threefry_seed_async(state_key unsafe.Pointer, state_counter unsafe.Pointer, state_result unsafe.Pointer, state_tracker unsafe.Pointer, seed unsafe.Pointer, cfg *config, events []*cl.Event) *cl.Event {
	if Synchronous { // debug
		ClCmdQueue.Finish()
		timer.Start("threefry_seed")
	}

	threefry_seed_args.Lock()
	defer threefry_seed_args.Unlock()

	threefry_seed_args.arg_state_key = state_key
	threefry_seed_args.arg_state_counter = state_counter
	threefry_seed_args.arg_state_result = state_result
	threefry_seed_args.arg_state_tracker = state_tracker
	threefry_seed_args.arg_seed = seed

	SetKernelArgWrapper("threefry_seed", 0, state_key)
	SetKernelArgWrapper("threefry_seed", 1, state_counter)
	SetKernelArgWrapper("threefry_seed", 2, state_result)
	SetKernelArgWrapper("threefry_seed", 3, state_tracker)
	SetKernelArgWrapper("threefry_seed", 4, seed)

	//	args := threefry_seed_args.argptr[:]
	event := LaunchKernel("threefry_seed", cfg.Grid, cfg.Block, events)

	if Synchronous { // debug
		ClCmdQueue.Finish()
		timer.Stop("threefry_seed")
	}

	return event
}
