package oclRAND

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for threefry_uint kernel invocation
type threefry_uint_args_t struct {
	arg_state_key     unsafe.Pointer
	arg_state_counter unsafe.Pointer
	arg_state_result  unsafe.Pointer
	arg_state_tracker unsafe.Pointer
	arg_output        unsafe.Pointer
	arg_data_size     int
	argptr            [6]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for threefry_uint kernel invocation
var threefry_uint_args threefry_uint_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	threefry_uint_args.argptr[0] = unsafe.Pointer(&threefry_uint_args.arg_state_key)
	threefry_uint_args.argptr[1] = unsafe.Pointer(&threefry_uint_args.arg_state_counter)
	threefry_uint_args.argptr[2] = unsafe.Pointer(&threefry_uint_args.arg_state_result)
	threefry_uint_args.argptr[3] = unsafe.Pointer(&threefry_uint_args.arg_state_tracker)
	threefry_uint_args.argptr[4] = unsafe.Pointer(&threefry_uint_args.arg_output)
	threefry_uint_args.argptr[5] = unsafe.Pointer(&threefry_uint_args.arg_data_size)
}

// Wrapper for threefry_uint OpenCL kernel, asynchronous.
func k_threefry_uint_async(state_key unsafe.Pointer, state_counter unsafe.Pointer, state_result unsafe.Pointer, state_tracker unsafe.Pointer, output unsafe.Pointer, data_size int, cfg *config, events []*cl.Event) *cl.Event {
	if Synchronous { // debug
		ClCmdQueue.Finish()
		timer.Start("threefry_uint")
	}

	threefry_uint_args.Lock()
	defer threefry_uint_args.Unlock()

	threefry_uint_args.arg_state_key = state_key
	threefry_uint_args.arg_state_counter = state_counter
	threefry_uint_args.arg_state_result = state_result
	threefry_uint_args.arg_state_tracker = state_tracker
	threefry_uint_args.arg_output = output
	threefry_uint_args.arg_data_size = data_size

	SetKernelArgWrapper("threefry_uint", 0, state_key)
	SetKernelArgWrapper("threefry_uint", 1, state_counter)
	SetKernelArgWrapper("threefry_uint", 2, state_result)
	SetKernelArgWrapper("threefry_uint", 3, state_tracker)
	SetKernelArgWrapper("threefry_uint", 4, output)
	SetKernelArgWrapper("threefry_uint", 5, data_size)

	//	args := threefry_uint_args.argptr[:]
	event := LaunchKernel("threefry_uint", cfg.Grid, cfg.Block, events)

	if Synchronous { // debug
		ClCmdQueue.Finish()
		timer.Stop("threefry_uint")
	}

	return event
}
