package oclRAND

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
	"unsafe"
)

// Stores the arguments for xorwow_seed kernel invocation
type xorwow_seed_args_t struct {
	arg_state_buf       unsafe.Pointer
	arg_g_jump_matrices unsafe.Pointer
	arg_seed            uint64
	argptr              [3]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for xorwow_seed kernel invocation
var xorwow_seed_args xorwow_seed_args_t

func init() {
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	xorwow_seed_args.argptr[0] = unsafe.Pointer(&xorwow_seed_args.arg_state_buf)
	xorwow_seed_args.argptr[1] = unsafe.Pointer(&xorwow_seed_args.arg_g_jump_matrices)
	xorwow_seed_args.argptr[2] = unsafe.Pointer(&xorwow_seed_args.arg_seed)
}

// Wrapper for xorwow_seed OpenCL kernel, asynchronous.
func k_xorwow_seed_async(state_buf unsafe.Pointer, g_jump_matrices unsafe.Pointer, seed uint64, cfg *config, events []*cl.Event) *cl.Event {
	if Synchronous { // debug
		ClCmdQueue.Finish()
		timer.Start("xorwow_seed")
	}

	xorwow_seed_args.Lock()
	defer xorwow_seed_args.Unlock()

	xorwow_seed_args.arg_state_buf = state_buf
	xorwow_seed_args.arg_g_jump_matrices = g_jump_matrices
	xorwow_seed_args.arg_seed = seed

	SetKernelArgWrapper("xorwow_seed", 0, state_buf)
	SetKernelArgWrapper("xorwow_seed", 1, g_jump_matrices)
	SetKernelArgWrapper("xorwow_seed", 2, seed)

	//	args := xorwow_seed_args.argptr[:]
	event := LaunchKernel("xorwow_seed", cfg.Grid, cfg.Block, events)

	if Synchronous { // debug
		ClCmdQueue.Finish()
		timer.Stop("xorwow_seed")
	}

	return event
}
