package opencl64

/*
 THIS FILE IS AUTO-GENERATED BY OCL2GO.
 EDITING IS FUTILE.
*/

import(
	"unsafe"
	"github.com/seeder-research/uMagNUS/cl"
	"github.com/seeder-research/uMagNUS/timer"
	"sync"
)


// Stores the arguments for threefry64_seed kernel invocation
type threefry64_seed_args_t struct{
	 arg_state_key unsafe.Pointer
	 arg_state_counter unsafe.Pointer
	 arg_state_result unsafe.Pointer
	 arg_state_tracker unsafe.Pointer
	 arg_seed unsafe.Pointer
	 argptr [5]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for threefry64_seed kernel invocation
var threefry64_seed_args threefry64_seed_args_t

func init(){
	// OpenCL driver kernel call wants pointers to arguments, set them up once.
	 threefry64_seed_args.argptr[0] = unsafe.Pointer(&threefry64_seed_args.arg_state_key)
	 threefry64_seed_args.argptr[1] = unsafe.Pointer(&threefry64_seed_args.arg_state_counter)
	 threefry64_seed_args.argptr[2] = unsafe.Pointer(&threefry64_seed_args.arg_state_result)
	 threefry64_seed_args.argptr[3] = unsafe.Pointer(&threefry64_seed_args.arg_state_tracker)
	 threefry64_seed_args.argptr[4] = unsafe.Pointer(&threefry64_seed_args.arg_seed)
	 }

// Wrapper for threefry64_seed OpenCL kernel, asynchronous.
func k_threefry64_seed_async ( state_key unsafe.Pointer, state_counter unsafe.Pointer, state_result unsafe.Pointer, state_tracker unsafe.Pointer, seed unsafe.Pointer,  cfg *config, events []*cl.Event) *cl.Event {
	if Synchronous{ // debug
		ClCmdQueue.Finish()
		timer.Start("threefry64_seed")
	}

	threefry64_seed_args.Lock()
	defer threefry64_seed_args.Unlock()

	 threefry64_seed_args.arg_state_key = state_key
	 threefry64_seed_args.arg_state_counter = state_counter
	 threefry64_seed_args.arg_state_result = state_result
	 threefry64_seed_args.arg_state_tracker = state_tracker
	 threefry64_seed_args.arg_seed = seed
	

	SetKernelArgWrapper("threefry64_seed", 0, state_key)
	SetKernelArgWrapper("threefry64_seed", 1, state_counter)
	SetKernelArgWrapper("threefry64_seed", 2, state_result)
	SetKernelArgWrapper("threefry64_seed", 3, state_tracker)
	SetKernelArgWrapper("threefry64_seed", 4, seed)
	

//	args := threefry64_seed_args.argptr[:]
	event := LaunchKernel("threefry64_seed", cfg.Grid, cfg.Block, events)

	if Synchronous{ // debug
		ClCmdQueue.Finish()
		timer.Stop("threefry64_seed")
	}

	return event
}

